# Generated by Django 5.1 on 2026-02-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
