# Generated by Django 5.1 on 2026-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_mediafile_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("camera", "Camera"),
                    ("whatsapp", "WhatsApp"),
                    ("screenshots", "Screenshots"),
                    ("instagram", "Instagram"),
                    ("downloads", "Downloads"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
