# Generated by Django 5.1 on 2026-02-24 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_alter_mediafile_options_alter_mediafile_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="share_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma separated tags", max_length=500
            ),
        ),
    ]
